# Q.8 Explain Purpose of Try and Catch block.

# try block: 
The try block is used to enclose the section of code where an error might occur. It allows you to specify the potentially risky code that needs error handling. If an error occurs within the try block, the normal flow of execution is immediately transferred to the corresponding catch block.

# catch block: 
The catch block follows the try block and is responsible for catching and handling any errors thrown within the try block. It defines an exception handling routine to execute when an error occurs. The catch block takes an error object as a parameter, which represents the error that occurred. You can access this object and perform actions such as logging the error, displaying an error message, or taking appropriate corrective measures.